### PR TITLE
Replace `node-http2` with `http2-wrapper`

### LINKED ISSUE #270: `node-http2` is deprecated. Use node's built in `http2`
https://www.npmjs.com/package/node-http2 points to https://github.com/kaazing/node-http2 which no long exists.

It originally forked https://github.com/molnarg/node-http2, which notes that as of Node v9, the built in `http2` can be used.

### PR DESCRIPTION
**Pull request by mhassan1**
This PR replaces the deprecated `node-http2` dependency with `http2-wrapper`. It also removes checks related to `0.x` versions of Node.js, since they are already unsupported.

Fixes #270.

### CODE REVIEW

**Comment by vavsab** [comment]
@vladikoff Could you please review this? 
Waiting for it to resolve CVE in [spectaql](https://github.com/anvilco/spectaql)

**Comment by vavsab** [comment]
@Krinkle Could you please help with merging this PR?

**Comment by vavsab** [comment]
@XhmikosR Could you please help here?

**Comment by XhmikosR** [comment]
It seems this breaks CI tests FYI @vladikoff

**Comment by vavsab** [comment]
@XhmikosR Forked from here and [fixed tests](https://github.com/gruntjs/grunt-contrib-connect/pull/291/commits/e6affe5fe243ff53151d7d9319a6e77016c8608c)
Please review this PR https://github.com/gruntjs/grunt-contrib-connect/pull/291

**Comment by mhassan1** [comment]
I've fixed the broken test

**Comment by XhmikosR** [comment]
LGTM now. But even if I merge it I don't have npm rights, so @vladikoff needs to take care of this.

**Comment by vladikoff** [comment]
Sorry for the delay, I was sick and just getting back into the swing of things

**Comment by vavsab** [comment]
@vladikoff thanks for answering! could you please publish it to npm so we could use fixed package?

**Comment by vladikoff** [comment]
@vavsab Hi, yeap done!

**Comment by vladikoff** [comment]
@XhmikosR I added you to npm maintainers also 🎉

**Pull request merged**
