### PR TITLE
Replace http2 with node-http2

### PR DESCRIPTION
**Pull request by jacopolanzoni**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jacopolanzoni: please sign the CLA otherwise I can't merge any of your patches. But it'd be faster for me at this point to just merge my branch :P

**Comment by XhmikosR** [comment]
Thanks for the contributions, but I'll go with my branch for now because it's faster and it's green.

**Comment by jacopolanzoni** [comment]
I did sign it, I am not sure what I am doing wrong...

untitled

**Comment by XhmikosR** [comment]
Your git user details are not the same I guess. See the CLA bot's comment.

**Comment by jacopolanzoni** [comment]
Thanks for your comment, but your behaviour does not seem to me very collaborative. I am grateful for the hints you are giving me, but closing my PRs and opening one with the same changes is not a fair behaviour in the open-source community.

**Comment by XhmikosR** [comment]
I didn't open a PR, I just decided to fix it myself, well because it was **a lot** faster. You made 4 PRs for this.

**Pull request closed without merging**
