### PR TITLE
Replace http2 with node-http2

### PR DESCRIPTION
**Pull request by jacopolanzoni**

### CODE REVIEW

**Comment by jacopolanzoni** [comment]
@XhmikosR Thanks for your correction to my previous PR. Please review the current one if you have time.

**Comment by XhmikosR** [comment]
@jacopolanzoni please fetch upstream, rebase and squash your patches.

**Comment by XhmikosR** [comment]
Also, please sign the CLA.

**Comment by XhmikosR** [comment]
If you can't do it, I can just push my branch https://github.com/gruntjs/grunt-contrib-connect/compare/node-http2

**Pull request closed without merging**
