### PR TITLE
Directory listing options

### PR DESCRIPTION
**Pull request by wizzyfx**
Added an option to configure directory listing options. See https://github.com/expressjs/serve-index#options for configuration options.

### CODE REVIEW

**Comment by vladikoff** [comment]
Awesome, could you update https://github.com/gruntjs/grunt-contrib-connect/blob/master/docs/connect-options.md

and then run `grunt`, that should regenerate the README.md

**Comment by wizzyfx** [comment]
Wow, 9 commits for 10 lines of code... Sorry for the mess :)

**Comment by vladikoff** [comment]
Previous comment still stands, please reopen if still want this.

**Comment by wizzyfx** [comment]
Sorry about that. I thought I have done what you have asked for. Updated connect-options.md and then ran grunt. Where did I do wrong? I'll check everything and then re-submit the PR tomorrow.

**Comment by vladikoff** [comment]
> Wow, 9 commits for 10 lines of code... Sorry for the mess :)

Hey yea need to squash those commits :)

**Comment by wizzyfx** [comment]
I'll open a new PR. This one is a mess :)

**Pull request closed without merging**
