### PR TITLE
Release 5.0.1

### PR DESCRIPTION
**Pull request by Krinkle**
* https://github.com/gruntjs/grunt-contrib-connect/issues/286

### CODE REVIEW

**Review by vladikoff — APPROVED** [review]
sorry for the delay!

**Comment by vladikoff** [comment]
let me know if you need help publishing this

**Comment by Krinkle** [comment]
@vladikoff I can merge and tag in Git but cannot publish to this package on npm yet. Do you want to do that?

**Comment by vladikoff** [comment]
@Krinkle done! thank you, sorry for the delay!

**Pull request merged**
