### PR TITLE
pass parameters to connect-livereload

### LINKED ISSUE #100: Allow options to be passed through to connect-livereload.
Is there any way to specify options for connect-livereload via the grunt-contrib-connect configuration? I'd like to change the livereload ignore list but I can't see a way to achieve it without overriding the middleware.

My apologies if there is something obvious I've missed.

Thanks!

### PR DESCRIPTION
**Pull request by Ins87**
closes #100

### CODE REVIEW

**Comment by sindresorhus** [comment]
Merge conflict needs to be fixed.

**Comment by Ins87** [comment]
Merge conflict solved

**Comment by sindresorhus** [comment]
Wrong indentation.

**Comment by Ins87** [comment]
You are right, sry for that. Fixed

.editorconfig would be nice

**Comment by Ins87** [comment]
Hi,
Will you check this?

**Comment by dsarrio** [comment]
Would love to see that merged, there are at least 3 issues topics about it. If author is absent or i don't know, may be just reject the PR and we will provide one new. Needs are only to be able to pass either a boolean/number or object to the livereload config option so one can configure underlying connect-livereload plugin. In my case i need to turn off compression, but for some others it is about exclusion rules.

Thanks in advance for any actions :)

**Comment by vladikoff** [comment]
Please reopen and rebase PR if you still want this merged

**Pull request closed without merging**
